### ISSUE TITLE
ForwardDynamicsTrainerの実装

### ISSUE THREAD

**Issue by myxyy** [MLShukai/ami#106]
# タスク内容

ForwardDynamicsクラスとForwardDynamicsTrainerを実装？
実装前に理解の整理が必要

* ForwardDymamicsModel
  - $a_t, z_t, h_t \rightarrow p(\hat{z_{t+1}}), h_{t+1}$の射影、Distributionへの変換
* ForwardDynamicsWrapper
  - forward/inferで扱いを変える
* ForwardDynamicsTrainer

### 達成条件

- [ ] ...

**Comment by myxyy** [comment]
https://github.com/MLShukai/ami/pull/114
にForwardDynamics, ForwardDynamicsWrapper周りだけ移動しました
Closeします

**Comment by myxyy** [comment]
PRの方と間違えました

**Comment by Geson-anko** [comment]
@myxyy Forward Dynamics Trainerに関していくつかの仕様があります。

* ObservationEncoderの取得: コンストラクタに`observation_encoder_name: ModelNames | None = None`を追加し、観測埋め込みモデルを取得できるようにしてください。今までの P-AMI<Q>の実装互換性を持たせるためです。

```py
class ForwardDynamicsTrainer:
    def __init__(self, observation_encoder_name: ModelNames | None = None):
        ...
    def on_model_wrappers_dict_attached(self) -> None:
        if self. observation_encoder_name is None:
            self.observation_encoder = None
        else:
            self.observation_encoder = self.get_frozen_model(self. observation_encoder_name)
    def train(self):
        for batch in self.data_loader:
            obs, ... = batch
            if self.observation_encoder is not None:
                with torch.no_grad():
                    obs = self.observation_encoder(obs)
```

* 損失の計算: 損失の計算に`Distribution.log_prob`を用いてください。

```py
class ForwardDynamicsTrainer:
    def train(self):
        for batch in data_loader:
            obs, ... = batch
            obs_dist, hidden = self.forward_dynamics(...)
            loss =  - obs_dist.log_prob(obs).mean() # obs_distが標準偏差が固定された Normalの場合、MSEに近似
```

**Comment by myxyy** [comment]
@Geson-anko 
すみませんコメント見逃していました
`observation_encoder`として`EncoderWrapper`を取得する場合`observation_encoder(obs)`は`Normal`になると思いますが
`rsample()`するかあるいは`infer()`を呼び出せばよいでしょうか？

**Comment by Geson-anko** [comment]
> @Geson-anko 
> 
> すみませんコメント見逃していました
> 
> `observation_encoder`として`EncoderWrapper`を取得する場合`observation_encoder(obs)`は`Normal`になると思いますが
> 
> `rsample()`するかあるいは`infer()`を呼び出せばよいでしょうか？

@myxyy `infer`を呼んでください

**Comment by Geson-anko** [comment]
> > @Geson-anko 
> > 
> > すみませんコメント見逃していました
> > 
> > `observation_encoder`として`EncoderWrapper`を取得する場合`observation_encoder(obs)`は`Normal`になると思いますが
> > 
> > `rsample()`するかあるいは`infer()`を呼び出せばよいでしょうか？
> 
> @myxyy `infer`を呼んでください

あ、なのでEncoderやForwardDynamicsを共通のGPUデバイスに転送する事を忘れずに
