### ISSUE TITLE
CuriosityPPOAgentにlogger追加

### ISSUE THREAD

**Issue by myxyy** [MLShukai/ami#167]
# タスク内容

CuriosityPPOAgentにTimeIntervalLoggerを追加する
ImageEncodingAgentにも一応追加？

### 達成条件

- [ ] 単純なテストに通る

**Comment by myxyy** [comment]
@Geson-anko 
CuriosityPPOAgentで記録する情報はvalueだけでしょうか？actionも記録しますか？

**Comment by Geson-anko** [comment]
valueも記録します。actionの記録は別に行います。

**Comment by Geson-anko** [comment]
ImageEncodingAgentへのLoggerの実装は要りません。
