### ISSUE TITLE
World Modelsの形式に従った AMIの実装

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami#201]
# タスク内容

World Modelsのモデル形式に従ったモデル設計を行う。ObservationEncoder, Forward Dynamicsは据え置きだが、Policyの入力を埋め込み観測 $z_t$, 隠れ状態 $h_t$ とする。

### CuriosityImagePPOAgent

観測埋め込みを観測の代わりとして方策に入力するオプションを作成する。名前は `use_embed_obs_for_policy`とするか

### PPOTrajectoryBuffer

`OBSERVATION`ではなく`EMBED_OBSERVATION`を観測として集める。
コンストラクタでobservation_keyを指定できるようにしても良いし、`use_embed_observation_as_observation`フラグで管理しても良い。

### PPOのモデル改良

World Modelsの論文では、方策モデルは 軽量なもので良いことが示されていた。こちらもそれに従う。
入力が埋め込み観測 $z_t: ( *, N_z)$ と スタックされた隠れ状態 $h_t: ( *, D, N_h)$ であるため、それぞれの次元数を合わせる線型層を適用した後に、depth方向に $[z_t, h_t]$と結合し、depth方向に対してGlobal畳み込み(カーネルサイズ D+1)を行う。

モデルのパターンを増やせるようにするために、n層のConv + Global Poolという構成をしても良い。カーネルサイズがD+1かつn=1の場合に、Global Convと一致するためである。
 
### スケッチ

```py
class ConcatFlattenedObservationAndStackedHidden(nn.Module):
    """Concatenates the flattened observation and stacked hidden states.
    
    Shape:
        - flattened_obs: (*, N)
        - stacked_hidden: (*, D, N)
        
        Return shape: (*, D+1, N) if transpose is False, else (*, N, D+1)
    """
    def __init__(self, traspose: bool = False) -> None:
        super().__init__()
        self.transpose = traspose

    def forward(self, flattened_obs: Tensor, stacked_hidden: Tensor) -> Tensor:
        out =  torch.cat([flattened_obs.unsqueeze(-2), stacked_hidden], dim=-2)
        if self.transpose:
            out = out.transpose(-2, -1)
        return out
```

### 達成条件

- [ ] ...

## 参考

https://worldmodels.github.io

**Comment by myxyy** [comment]
https://github.com/MLShukai/ami/pull/203 を含めて確認しました
観測zをdepth方向に複製してstacked hiddenと結合してdepth方向の1次元畳み込みをするというやりかたには疑問を持っており、
画像のX方向、Y方向に隣接したピクセルが関連した情報を持つように、$(*, D, N)$の形のstacked hiddenがD方向に隣接した数値が関連した情報を持っているわけではないからです。
計算コストが許すのであれば全てのdepthから全結合を取るか、そうでなければSConvの一番深いレイヤー、3層で構成されるなら2層目の隠れ状態だけ持ってくるというのを想定していました。

**Comment by Geson-anko** [comment]
@myxyy なるほど、わかりました。確かに、各層の隠れ状態の同じチャネル位置が同様の情報を持っているバイアスはありませんね。
ただ $D \times N$ のユニット数が全結合で処理するとかかってしまうので、もうちょいマシな方法がないかと思います。マルチヘッドでやってみる？

ただ、条件として、
* 全ての要素を用いること。複数のhiddenがあるなら全て用いて行動を決定するべき。下手に特定の値を抽出する前処理行為はモデルの性能を劣化させるだけである。

というのが深層モデルを適用する際の通例となっているので、最初は全ての要素を用いたと思っています。
