### ISSUE TITLE
メインスレッドWeb API提案

### ISSUE THREAD

**Issue by yuntan** [MLShukai/ami#26]
# 提案内容
メインスレッドのインタフェースとなるWeb APIを提案する。

# Web API
- APIエンドポイントをGET/POSTするとJSONを返すものとする。
- GETで状態確認を行う（システムの状態を変更しない）。
- POSTで命令を行う（システムの状態を変更する）。

## `GET /api/status`
システムの状態を返す。

```sh
> curl -H GET http://localhost:8080/api/status
{"status": "active"}
{"status": "paused"}
{"status": "stopped"}
```

## `POST /api/start`
システムを開始する。

```sh
> curl -H POST http://localhost:8080/api/start
{"result": "ok", "status": "active"}
{"result": "error", "status": "stopped", "error": "..."} # 操作が失敗した場合
```

## `POST /api/pause`
システムを一時停止する。

```sh
> curl -H POST http://localhost:8080/api/pause
{"result": "ok", "status": "paused"}
{"result": "error", "status": "active", "error": "..."} # 操作が失敗した場合
```

## `POST /api/resume`
システムを一時停止状態から復帰する。

```sh
> curl -H POST http://localhost:8080/api/resume
{"result": "ok", "status": "active"}
{"result": "error", "status": "paused", "error": "..."} # 操作が失敗した場合
```

## `POST /api/shutdown`
システムを終了する。

```sh
> curl -H POST http://localhost:8080/api/shutdown
{"result": "ok", "status": "stopped"}
{"result": "error", "status": "active", "error": "..."} # 操作が失敗した場合
```

# 状態遷移図
```mermaid
sequenceDiagram
  stopped ->> active: POST /api/start
  active ->> paused: POST /api/pause
  paused ->> active: POST /api/resume
  active ->> stopped: POST /api/shutdown
  paused ->> stopped: POST /api/shutdown
```

上記以外の操作が行われた場合エラーを返す。

# タスク
- [X] `ThreadControler` を参考にブラッシュアップ

**Comment by Geson-anko** [comment]
@yuntan `ThreadController`のスケッチへのリンクもここに置いときますね。
https://enormous-sage-ead.notion.site/ab9140759e264002874a3addd3d42726

**Comment by Geson-anko** [comment]
@yuntan 今の所、API名に関しては、次の命名にしたいと考えています。

* `shutdown`: システムを終了する。
* `pause`: システムを一時停止する
* `resume`: システムを再開する。

statusはこんな感じです。

* `active`: システムが稼働中 (`running`でも良いかもしれませんが、`ThreadController`と命名を合わせる方が良いかなと)
* `paused`: 一時停止
* `stopped`: システムが終了した。または起動していない。

**Comment by Geson-anko** [comment]
ちなみにシステムの起動そのものは、 `python train.py` で行おうと考えていました。Web APIから起動できるようにした方が、色々と便利かもしれません。どうするかはもう少し検討したいところ。

**Comment by yuntan** [comment]
@Geson-anko 命名を修正しました。

システムの起動については、

- `python train.py` で `active` に
- `python train.py --stopped` で `stopped` に
- `python train.py --paused` で `paused` に

というのはどうでしょうか？stoppedとpausedを両方実装する必要があるのかは、起動の具体的な処理を把握していないので分かりませんが。

**Comment by yuntan** [comment]
@Geson-anko メインスレッドはどちらに実装すれば良いですか？

**Comment by Geson-anko** [comment]
@yuntan 返信が遅くなってすみません．pythonのソースにどういった形で実装するかに関しては，まだ検討していません．卒論の執筆で中々時間が取れていないので，Web APIだけのサンプルコード等を用意していただければ，具体的にどう実装するか答えられると思います．ちなみに `train.py`はこのような実装を想定しています．
https://github.com/MLShukai/PrimitiveAMI/blob/main/src/train.py
