### ISSUE TITLE
Loggingに関して

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami#29]
## 概要

pythonの `logging`モジュールを使用した システムログの記録方法について仕様をまとめます。

## 背景と目的

非同期AMI Systemでは、複数のスレッド（メインスレッド、学習スレッド、推論スレッド）が常に処理を行っています。このスレッドは必要に応じてログを出力しますが、デバッグの都合上、スレッドごとに分けてログが記録されていることが望ましいです。（ただしコンソールは一つしかありませんから、そこが混ざるのは仕方のない事とします。）

本タスクの目的は、スレッドごとにログを分けて出力するための機能を実装することが目的です。

### スレッドロガー
主に `logging`モジュールを用いた実装を考えます。それぞれのスレッドに専用の親ロガーを取得できるようのします。後の **##参考** セクションにログの伝播について軽く記述しています。

```py
import logging

def get_thread_logger(thread_name: str, logger_name: str) -> logging.Logger:
    return logging.getLogger(f"{thread_name}.{logging_name}")

def get_main_thread_logger(name: str) -> logging.Logger:
    return get_thread_logger("main", name)

# InferenceやTrainingスレッドのものも同様に。
```

`main.*`という名前のロガーにファイルハンドラーを設定し、メインスレッド上での処理のログを `get_main_thread_logger`で取得したロガーを用いて行えば、メインスレッド上でのログを全て取得することができるようになります。

### Handler

ログのコンソールへの出力や、ファイルへの出力に関しては、`StreamHandler`や、`RotatingFileHandler`を用います。
RootLoggerには`StreamHandler`と`RotatingFileHandler`を、それぞれのスレッドのロガーには `RotatingFileHandler`のみを設定します。

NOTE: AMIは長期間稼働することを想定したシステムのため、無限にファイルに書き込み続ける`FileHandler`は使えません。

### dictConfig

[`hydra`](https://hydra.cc/docs/0.11/configure_hydra/logging/)というハイパラ管理ツールを使用する関係上、yamlやjsonなどの辞書形式のconfigオブジェクトから、ハンドラーなどを設定できる必要があります。

最終的には、`logging.dictConfig`を使って設定ファイルを受け渡し、適切にファイルやコンソールに出力することが、タスクになります。

## タスク

- [x] 各スレッド専用のロガーを取得できる
- [x] `dictConfig`を用いて、Handler等を設定できる。
  - [x] RootLoggerには `StreamHandler`と`RotatingFileHandler`が設定された。
  - [x] 各スレッドのロガーには `RotatingFileHandler`が設定された
- [x] 実装した機能が期待する動作を取った。

## 参考

* loggingモジュール: https://docs.python.org/ja/3.11/library/logging.html
* logging チュートリアル: https://docs.python.org/ja/3.11/howto/logging.html
* configオブジェクトを用いた loggingのカスタマイズ: https://docs.python.org/ja/3/howto/logging.html#configuring-logging
* dictConfigについて: https://docs.python.org/ja/3/library/logging.config.html#logging.config.dictConfig

### `logging`のログの伝搬

loggingモジュールは、ロガーの名前をドット `.` パスで区切り、階層的にログを管理する機能があります。
全てのログは通常は RootLogger (名前はなし）まで伝播されます。すなわち、全てのログに関する処理（フォーマッタやファイル出力など
）は、RootLoggerに設定すると良いことになります。
`a.b.c` という名前のロガーから送信されたログは、`a`という名前のロガーにも通常は伝播されます。
`d.b.c` という名前のロガーから送信されたログは、もちろん `a`という名前のロガーには伝播されません。

**Comment by yuntan** [comment]
複数のスレッドからアクセスしても大丈夫か気になりましたが、 `Logger` はスレッドセーフとあるので大丈夫そうですね。

[スレッドセーフ性](https://docs.python.org/ja/3.11/library/logging.html#thread-safety)

**Comment by yuntan** [comment]
@Geson-anko Handlerについて、[`RotatingFileHandler`](https://docs.python.org/ja/3.11/library/logging.handlers.html#rotatingfilehandler) と [`TimedRotatingFileHandler`](https://docs.python.org/ja/3.11/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler) とがありますが、どちらが良いでしょうか？

クラス | 挙動
-- | --
`RotatingFileHandler` | ファイルサイズでログを分割
`TimedRotatingFileHandler` | 時間間隔でログを分割

**Comment by yuntan** [comment]
[`warnings` モジュールとの統合](https://docs.python.org/ja/3.11/library/logging.html#integration-with-the-warnings-module)を使うとPytorchのwarningもログに出せそう。

**Comment by Geson-anko** [comment]
> @Geson-anko Handlerについて、[`RotatingFileHandler`](https://docs.python.org/ja/3.11/library/logging.handlers.html#rotatingfilehandler) と [`TimedRotatingFileHandler`](https://docs.python.org/ja/3.11/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler) とがありますが、どちらが良いでしょうか？
> 
> 
> 
> クラス | 挙動
> 
> -- | --
> 
> `RotatingFileHandler` | ファイルサイズでログを分割
> 
> `TimedRotatingFileHandler` | 時間間隔でログを分割

@yuntan 用途的にはTimedの方が良いですね。ぱみきゅーは現実時間で動き続けるので、一定時間毎にログがまとまっていた方が管理がしやすそうです。

**Comment by yuntan** [comment]
@Geson-anko  プログラム内で出力したい情報と関数の対応をまとめておくと、実装時に迷わなくて良いかなと思うのですが、どうでしょうか？以下のような感じです。

出力したい情報 | 関数
-- | --
プログラムの診断（デバッグ）のための詳細情報 | `debug()`
通常の処理中に発生したイベントの報告 | `info()`
警告の発行 | `warning()`
抑制されたエラーの情報 | `error()`
例外の情報 | `exception()`
プログラムの継続が不可能なエラーの情報 | `critical()`

**Comment by Geson-anko** [comment]
@yuntan 情報の整理ありがとうございます。そのようにお願いします。
`warning`はあまり使用しないのですが、loggingモジュールに統合しておくは良いかと。

**Comment by yuntan** [comment]
実装に取りかかっています。

@Geson-anko 設定ファイルはどこに入れれば良いですか？hydraの設定ファイルと統合する必要があるとのことですが、hydraの設定ファイルが見当たりません。

**Comment by Geson-anko** [comment]
`hydra`は後で追加します。そうですね、`samples`フォルダの中に yaml形式で記述してください。

**Comment by Geson-anko** [comment]
こんな感じで 設定が書かれる想定です。https://github.com/MLShukai/PrimitiveAMI/blob/main/configs/hydra/default.yaml

hydraに関しては、いつかちゃんと資料にまとめないとですね
https://hydra.cc/docs/0.11/configure_hydra/logging/
