### ISSUE TITLE
開発環境セットアップのドキュメンテーション書く

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami#57]
# タスク内容

ochaさんが書いてくれたNotionのドキュメンテーションを元に、AMI用の、OS、Steam(VRChat)、OBS、**Docker**などのインストール方法をまとめたドキュメンテーションを作る。

https://confusion-universe-c5b.notion.site/Ubuntu22-04-b7b5f0be1abb40c2a60debae4f3e6043

### 達成条件

- [ ] ドキュメンテーションが作成された。
- [ ] 1人以上の開発者がその手順に従って開発環境をセットアップした。

**Comment by yuntan** [comment]
[ ] ドキュメントの検証（実際にローカルに環境立ち上げ） @yuntan

**Comment by Geson-anko** [comment]
@yuntan 一応 PRにドキュメントを記述しているので、足りないところはコミットしていただければ幸いです。
https://github.com/MLShukai/ami/pull/59
