### ISSUE TITLE
VAE Encoderのリファクタリング

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami#58]
# タスク内容

`vae.py`のEncoderクラスに、明示的に`mean`, `sigma`を出力する`nn.Linear`を実装する。

### 背景
2024/02/16 現在、`base_model`の出力を `torch.chunk`で2分割して`mean`, `sigma`としているが、`base_model`の出力層が必ずしも線形層である保証はない。インスタンス生成時に明示的に`base_model`のチャネル数を2倍にしなければならないことも問題である。

### 提案
次の用に変更する。

```py
class Encoder(nn.Module):
     def __init__(self, base_model: nn.Module, latent_dim: int) -> None:
         super().__init__()
         self.base_model = base_model
         self.latent_dim = latent_dim
         self.mean = nn.Linear(latent_dim, latent_dim)
         self.sigma = nn.Linear(latent_dim, latent_dim)

     def forward(self, x: torch.Tensor) -> Normal:
         ... # mean, sigma -> std
         return Normal(mean, std)
```

### 達成条件

- [ ] Encoderがリファクタリングされた
- [ ] テストが修正された。

**Comment by myxyy** [comment]
現時点では問題ありませんが、Encoderクラスと比べてDecoderクラスが殆ど何もしてないのが気になりますね
base_modelを取る形をやめてEncoder/Decoderでモデルまで持ってしまってConv2dEncoder, Conv2dDecoderとしたい気持ちがあります

**Comment by Geson-anko** [comment]
@myxyy じゃあ Normal Headみたいな名前のレイヤーがあるとよいですね。

**Comment by myxyy** [comment]
@Geson-anko 
↑ Conv2dEncoder/Decoderを作ってみました  
NormalHeadについてはちょっと考えましたがEncoder/Decoderが完全にモデルを定義できる以上必要性が薄いかなと思い入れていません

**Comment by Geson-anko** [comment]
@myxyy 再利用性があがるかと思いましたが、メンテコストも増加するので現段階ではやらない方がいいかもしれません。
