### ISSUE TITLE
Image Bufferの作成

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami#60]
# タスク内容

VAEの学習のために画像を集める `DataBuffer`クラスを作成する。
実装の参考は PrimitiveAMI の`ObsDataCollector`を参考にしてほしい。
https://github.com/MLShukai/PrimitiveAMI/blob/main/src/data_collectors/obs_data_collector.py

`ami/data/buffers/image_buffer.py`に`BaseDataBuffer`を継承した`ImageBuffer`クラスを作成し、次のメソッドを実装する。

- `init`: `__init__`はオーバライドしてはいけない。バッファのサイズ、初期化などを行う
- `add`: ObservationをStepDataから取り出し (`StepData[DataKeys.OBSERVATION`)、内部バッファに保存する。
- `concatenate`: 新たなバッファと結合する処理。二つのバッファの中から、バッファサイズ以下の制約のもとランダムにデータを混ぜ、結合する。
- `make_dataset`: 画像テンソルを提供するデータセットを返す。`TensorDataset`が良い

### 達成条件

- [ ] `ImageBuffer`クラスが実装された
- [ ] テストコードによる自動動作確認処理が行われた。データが集められること、結合できること、データセットが取り出せることを確認した。

**Comment by myxyy** [comment]
`StepData(dict[str, Any])`

**Comment by myxyy** [comment]
`StepData(dict[str, Any])`の実装見ていて思ったんですがこれは`StepData(dict[DataKeys, Any])`のようには型は付けられないようなものでしょうか？
`DataKeys(StrEnum)`を定義しておいてそれに関する型制約が付けられないというのは`StrEnum`で定義する意味を半分くらい失ってる感じがしますが

**Comment by myxyy** [comment]
ImageBufferは将来的にはマルチモーダルに拡張されるものでしょうか？
別モーダルは別のバッファに溜めるとすると時系列を合わせる仕組みが別で必要になりそうです

**Comment by Geson-anko** [comment]
> `StepData(dict[str, Any])`の実装見ていて思ったんですがこれは`StepData(dict[DataKeys, Any])`のようには型は付けられないようなものでしょうか？ `DataKeys(StrEnum)`を定義しておいてそれに関する型制約が付けられないというのは`StrEnum`で定義する意味を半分くらい失ってる感じがしますが

型付けして良いです。 `StepData`定義時に `DataKeys`を定義しなかったのでそのまま残っています。

**Comment by Geson-anko** [comment]
> ImageBufferは将来的にはマルチモーダルに拡張されるものでしょうか？ 別モーダルは別のバッファに溜めるとすると時系列を合わせる仕組みが別で必要になりそうです

これは 昨日 VRChatでお話しした通りですね。 いろんなモーダルを貯められるようにして良いかと思います。RandomBufferとして汎用的なクラスを作っておいて良いかもしれないです。

**Comment by myxyy** [comment]
@Geson-anko 
`concatenate`について確認です
既存バッファに後続のバッファを流し込むような使い方をするとして、後続バッファの要素を一つずつ既存バッファにaddするのが適切そうでしょうか？

**Comment by Geson-anko** [comment]
> @Geson-anko `concatenate`について確認です 既存バッファに後続のバッファを流し込むような使い方をするとして、後続バッファの要素を一つずつ既存バッファにaddするのが適切そうでしょうか？

@myxyy 
そのようにしても処理上はあまり問題ないかと。
listで管理しているのであれば、二つのリストを結合し、そこから`buffer_size`分のランダムに取得するという処理の方が **結合** 操作を *well* に 表しているかもしれません。( `old_buffer + new_buffer`をした上で、`indices = shuffled(arange(concat_length))[:buffer_size]`)
可読性が高い記述をお願いします。
